version = "3.10.7"
runner.dialect = scala3

style = defaultWithAlign
maxColumn = 120
indent.main = 2
align.openParenDefnSite = false
align.openParenCallSite = false
danglingParentheses.preset = true
#indent.infix = spray
project.excludeFilters = [".*\\.sbt"]
rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers, prefercurlyfors]
#unindentTopLevelOperators = true
importSelectors = singleLine
spaces.afterKeywordBeforeParen = true
lineEndings = unix
newlines.penalizeSingleSelectMultiArgList = false
newlines.alwaysBeforeElseAfterCurlyIf = false
binPack.literalArgumentLists = false
runner.optimizer.forceConfigStyleMinArgCount = 1